### ISSUE TITLE
Risk levels for validators

### ISSUE THREAD

**Issue by joyboyisfree** [thevantageproject/PolkaAnalytics#59]
Determine the logic for calculating "Risk level" for every validator based on information like self stake, total stake, how long has the validator been operational, number of slashes, etc.

Categorization of validators as:

Safe (0-5)
Low Risk (5-20)
Medium Risk (20-50)
High Risk (50-80)
Unsafe (80-100) - Cap at 100

Detailed documentation: https://www.notion.so/Risk-score-logic-determination-1c151b56576246a9acfa46b6cc0e7e31

### Inputs

- Validator address (a)
    - Own stake (o)
    - Total stake (w)
    - Other stake (e)
    - Number of backers (n)
    - Number of slashes (s)
    - Time in months → integer truncated (t)

### Output

- Risk score (r)

### Key insights

- o ∝ 1/r
- w ∝ 1/r
- e ∝ 1/r
- n ∝ 1/r
- s ∝ r

### Equation

For creating equation images, [https://www.codecogs.com/latex/eqneditor.php](https://www.codecogs.com/latex/eqneditor.php) was used.

**If t >= 1**

![image.png](https://images.zenhubusercontent.com/5ea66c27c12ee929e35ae529/68ba4f4a-d382-4117-993c-121e77b976c9)

The above equation allows a validator to recover his reputation by performing as a good actor for a long time if they get slashed.

I personally prefer the first one, because IMO everyone should be allowed the opportunity to change.

OR

![image.png](https://images.zenhubusercontent.com/5ea66c27c12ee929e35ae529/ffe110ff-3c12-4846-be12-cdc8c06636c4)

The above equation treats being slashed as a cardinal sin.

**If t == 0**

Default to "extremely high risk" or "not enough data to calculate risk"

**Comment by saumyakaran** [comment]
Detailed documentation: https://www.notion.so/Risk-score-logic-determination-1c151b56576246a9acfa46b6cc0e7e31

### Inputs

- Validator address (a)
    - Own stake (o)
    - Total stake (w)
    - Other stake (e)
    - Number of backers (n)
    - Number of slashes (s)
    - Time in months → integer truncated (t)

### Output

- Risk score (r)

### Key insights

- o ∝ 1/r
- w ∝ 1/r
- e ∝ 1/r
- n ∝ 1/r
- s ∝ r

### Equation

For creating equation images, [https://www.codecogs.com/latex/eqneditor.php](https://www.codecogs.com/latex/eqneditor.php) was used.

**If t >= 1**

![image.png](https://images.zenhubusercontent.com/5ea66c27c12ee929e35ae529/68ba4f4a-d382-4117-993c-121e77b976c9)

The above equation allows a validator to recover his reputation by performing as a good actor for a long time if they get slashed.

I personally prefer the first one, because IMO everyone should be allowed the opportunity to change.

OR

![image.png](https://images.zenhubusercontent.com/5ea66c27c12ee929e35ae529/ffe110ff-3c12-4846-be12-cdc8c06636c4)

The above equation treats being slashed as a cardinal sin.

**If t == 0**

Default to "extremely high risk" or "not enough data to calculate risk"

**Comment by joyboyisfree** [comment]
Closing in favor of https://github.com/buidl-labs/polka-analytics-api/issues/77
