### ISSUE TITLE
4. Product analytics & SEO

### ISSUE THREAD

**Issue by saumyakaran** [thevantageproject/PolkaAnalytics#7]
Tasks:

- [x] Track events to determine user flow
- Track if users use the staking guide
- Track if users change the input value
- ~Track if users copy the address of validators~
- Track if users open the specific views for validators and nominators
- Track if users go to the help center

- [x] Use a custom domain to allow google to crawl and index the web app

**Comment by prastut** [comment]
https://twitter.com/GoodMarketingHQ/status/1207295677279150080?s=20

**Comment by prastut** [comment]
@bhaskarSingh product tracking is important before sharing with early adopters since we need to get data about how people are using the product. Otherwise there is no way to understand when people clicked on the link did they actually try out the product? 

Currently, I only need tracking around 
- [x] Landed on home page: 
- [x] Landed on a validator specific view
- [x] Landed on a nominator specific view

**Comment by bhaskarSingh** [comment]
@prastut  I have already added events to track home, validator and nominator page view, and also the above stated by @saumyakaran  currently amplitude id is linked with @saumyakaran , if you want it to be linked to your account please share your amplitude id.

**Comment by bhaskarSingh** [comment]
@prastut  confirm if events are being logged correctly or not via amplitude

**Comment by joyboyisfree** [comment]
- [x] Site to be indexed by google @bhaskarSingh
